gulya_opa_jokes = ['Gulya opa is so fat that her bellybutton gets home 15 minutes before she does.',
                   "Gulya opa is so fat that when she was diagnosed with a flesh-eating disease, the doctor gave her ten years to live.",
                   "Gulya opa is so fat that the National Weather Service names each one of her farts.",
                   "Gulya opa is so fat that when she wears a yellow raincoat, people yell 'taxi!'",
                   "Gulya opa is so fat and dumb that the only reason she opened her email was because she heard it "
                   "contained spam.",
                   "Gulya opa is so fat she threw on a sheet for Halloween and went as Antarctica.",
                   "Gulya opa is so fat that she looked up cheat codes for Wii Fit",
                   "Gulya opa is so fat that the only exercise she gets is when she chases the ice cream truck.",
                   "Gulya opa is so fat that she sat on a dollar and squeezed a booger out George Washington's nose.",
                   "Gulya opa is so fat that when she gets in an elevator, it has to go down.",
                   "Gulya opa is so fat that when her beeper goes off, people think she's backing up.",
                   "Gulya opa is so fat that she has to iron her pants on the driveway.",
                   "Gulya opa is so fat that she left the house in high heels and came back wearing flip flops.",
                   "Gulya opa is so fat that people jog around her for exercise.",
                   "Gulya opa is so fat that she was floating in the ocean and Spain claimed her for the New World.",
                   "Gulya opa is so fat that when she walked in front of the TV, I missed 3 seasons of Breaking Bad.",
                   "Gulya opa is so fat that you have to grease the door frame and hold a twinkie on the other side "
                   "just to get her through!",
                   "Gulya opa is so fat that that when she sits on the beach, Greenpeace shows up and tries to tow "
                   "her back into the ocean...",
                   "Gulya opa is so fat that when she bungee jumps, she brings down the bridge too.",
                   "Gulya opa is so fat that when she talks to herself, it's a long distance call.",
                   "Gulya opa is so fat that the last time she saw 90210, it was on a scale.",
                   "Gulya opa is so fat that light bends around her.",
                   "Gulya opa is so fat that I took a picture of her last Christmas and it's still printing!",
                   "Gulya opa is so fat that when she sat on Wal-Mart, she lowered the prices.",
                   "Gulya opa is so fat that when she sat on an iphone, it turned into an ipad.",
                   "Gulya opa is so fat that even god can't lift her spirit.",
                   "Gulya opa is so fat that she gets group insurance.",
                   "Gulya opa is so fat that she was zoned for commercial development.",
                   "Gulya opa is so fat that she walked into the Gap and filled it.",
                   "Gulya opa is so fat that she comes at you from all directions.",
                   "Gulya opa is so fat that when she climbed onto a diving board at the beach, the lifeguard told your dad 'sorry, you can't park here'.",
                   "Gulya opa is so fat that her cereal bowl came with a lifeguard.",
                   "Gulya opa is so fat that she looks like she's smuggling a Volkswagen.",
                   "Gulya opa is so fat that when she got her shoes shined, she had to take the guy's word for it.",
                   "Gulya opa is so fat that when she sings, it's over for everybody.",
                   "Gulya opa is so fat that when she ran away, they had to use all four sides of the milk carton to display her picture.",
                   "Gulya opa is so fat that when she was growing up she didn't play with dolls, she played with midgets.",
                   "Gulya opa is so fat that she uses two buses for roller-blades.",
                   "Gulya opa's so fat she blew up the Death Star.",
                   "Gulya opa is so fat that when she goes to a buffet, she gets the group rate.",
                   "Gulya opa is so fat that she has to put her belt on with a boomerang.",
                   "Gulya opa is so fat that she broke the Stairway to Heaven.",
                   "Gulya opa is so fat that she doesn't eat with a fork, she eats with a forklift.",
                   "Gulya opa is so fat that the last time the landlord saw her, he doubled the rent.",
                   "Gulya opa is so fat that Weight Watchers won't look at her.",
                   "Gulya opa is so fat that the highway patrol made her wear a sign saying 'Caution! Wide Turn'.",
                   "Gulya opa is so fat that when she sits around the house, she SITS AROUND THE HOUSE!",
                   "Gulya opa is so fat that when she steps on a scale, it reads 'one at a time, please'.",
                   "Gulya opa is so fat that she fell in love and broke it.",
                   "Gulya opa is so fat that when she gets on the scale it says 'We don't do livestock'.",
                   "Gulya opa is so fat that when she tripped on 4th Ave, she landed on 12th.",
                   "Gulya opa is so fat that God couldn't light the Earth until she moved!",
                   "Gulya opa is so fat that even Bill Gates couldn't pay for her liposuction!",
                   "Gulya opa is so fat that she has to pull down her pants to get into her pockets.",
                   "Gulya opa is so fat that she was born on the fourth, fifth, and sixth of June.",
                   "Gulya opa is so fat that she could fall down and wouldn't even know it.",
                   "Gulya opa is so fat that the sign inside one restaurant says, “Maximum occupancy: 300, or Gulya opa.”",
                   "Gulya opa is so fat that she puts mayonnaise on aspirin.",
                   "Gulya opa is so fat that she was born with a silver shovel in her mouth.",
                   "Gulya opa is so fat that when she hauls ass, she has to make two trips.",
                   "Gulya opa is so fat that she had to go to Sea World to get baptized.",
                   "Gulya opa is so fat that her belly button's got an echo.",
                   "Gulya opa is so fat that when she turns around people throw her a welcome back party.",
                   "Gulya opa is so fat that her belly button doesn't have lint, it has sweaters.",
                   "Gulya opa is so fat that a picture of her would fall off the wall.",
                   "Gulya opa is so fat that when she takes a shower, her feet don't get wet.",
                   "Gulya opa is so fat that she puts on her lipstick with a paint-roller!",
                   "Gulya opa is so fat that she could sell shade.",
                   "Gulya opa is so fat that I ran around her twice and got lost.",
                   "Gulya opa is so fat that the shadow of her butt weighs 100 pounds.",
                   "Gulya opa is so fat that when she's standing on the corner police drive by and yell, “Hey, break it up.”",
                   "Gulya opa is so fat that her blood type is Ragu.",
                   "Gulya opa is so fat that when she runs the fifty-yard dash she needs an overnight bag.",
                   "Gulya opa is so fat that she can't even fit into an AOL chat room.",
                   "Gulya opa is so fat when she goes skydiving she doesn't use a parachute to land, she uses a twin-engine plane!",
                   "Gulya opa is so fat MTX audio's subwoofers couldn't rattle her bones!",
                   "Gulya opa is so fat her headphones are a pair of PA speakers connected to a car amplifier.",
                   "Gulya opa is so fat that she doesn't have a tailor, she has a contractor.",
                   "Gulya opa is so fat that eating contests have banned her because she is unfair competition.",
                   "Gulya opa is so fat that she measures 36-24-36, and the other arm is just as big.",
                   "Gulya opa is so fat that she gets her toenails painted at Lucky's Auto Body.",
                   "Gulya opa is so fat that when she goes to an amusement park, people try to ride HER!",
                   "Gulya opa is so fat that when she jumps up in the air she gets stuck!",
                   "Gulya opa is so fat that she has more Chins than a Chinese phone book!",
                   "Gulya opa is so fat that she influences the tides.",
                   "Gulya opa is so fat that when she plays hopscotch, she goes 'New York, L.A., Chicago...'",
                   "Gulya opa is so fat that NASA has to orbit a satellite around her!",
                   "Gulya opa is so fat that when she sits on my face I can't hear the stereo.",
                   "Gulya opa is so fat that they have to grease the bath tub to get her out!",
                   "Gulya opa is so fat that she's on both sides of the family!",
                   "Gulya opa is so fat that at the zoo, the elephants throw HER peanuts.",
                   "Gulya opa is so fat you have to roll over twice to get off her.",
                   "Gulya opa is so fat that she sets off car alarms when she runs.",
                   "Gulya opa is so fat that she cant reach into her back pocket.",
                   "Gulya opa is so fat that she has her own gravity field.",
                   "Gulya opa is so fat that she stepped on a rainbow and made Skittles.",
                   "Gulya opa is so fat that the only pictures you have of her were taken by satellite cameras.",
                   "Gulya opa is so fat that when she wears a 'Malcolm X' T-shirt, helicopters try to land on her back!",
                   "Gulya opa is so fat that it took Usain Bolt 3 years to run around her.",
                   "Gulya opa so fat that she sweats more than a dog in a chinese restaurant.",
                   "Gulya opa so fat, that went she stepped in the water, Thailand had to declare another tsunami warning.",
                   "Gulya opa is so fat that that she cant tie her own shoes.",
                   "Gulya opa is so fat that when she lays on the beach, people run around yelling Free Willy.",
                   "Gulya opa is so fat that she uses redwoods to pick her teeth",
                   "Gulya opa is so fat that she cut her leg and gravy poured out",
                   "Gulya opa is so fat that she was in the Macy's Thanksgiving Day Parade... wearing ropes.",
                   "Gulya opa is so fat that she went on a light diet. As soon as it's light she starts eating.",
                   "Gulya opa is so fat that she's half Italian, half Irish, and half American.",
                   "Gulya opa is so fat that her waist size is the Equator.",
                   "Gulya opa is so fat that she can't even jump to a conclusion.",
                   "Gulya opa is so fat that she uses a mattress for a tampon.",
                   "Gulya opa is so fat that when she got hit by a bus, she said, 'Who threw that rock at me?'",
                   "Gulya opa is so fat that we went to the drive-in and didn't have to pay for her because we dressed her up as a Toyota.",
                   "Gulya opa is so fat that when she was born, she gave the hospital stretch marks.",
                   "Gulya opa is so fat that she was cut from the cast of E.T., because she caused an eclipse when she rode the bike across the moon.",
                   "Gulya opa is so fat that when you get on top of her your ears pop.",
                   "Gulya opa is so fat that she got hit by a car and had to go to the hospital to have it removed.",
                   "Gulya opa is so fat that she eats 'Wheat Thicks'.",
                   "Gulya opa is so fat that we're in her right now!",
                   "Gulya opa is so fat that she went to the movie theatre and sat next to everyone.",
                   "Gulya opa is so fat that she has been declared a natural habitat for condors.",
                   "Gulya opa is so fat that when she wants to shake someones hand, she has to give directions!",
                   "Gulya opa is so fat that even Dora can't explore her!",
                   "Gulya opa is so fat that when she gets on the scale it says 'to be continued'.",
                   "Gulya opa is so fat that when she goes to a restaurant, she looks at the menu and says 'okay!'",
                   "Gulya opa is so fat that even Chuck Norris couldn't run around her.",
                   "Gulya opa is so fat that her neck looks like a dozen hot dogs!",
                   "Gulya opa is so fat that when she bungee jumps she goes straight to hell!",
                   "Gulya opa is so fat that she's got her own area code!",
                   "Gulya opa is so fat that she looks like she's smuggling a Volkswagen!",
                   "Gulya opa is so fat that she has to buy three airline tickets.",
                   "Gulya opa is so fat that whenever she goes to the beach the tide comes in!",
                   "Gulya opa is so fat that she's got Amtrak written on her leg.",
                   "Gulya opa is so fat that her legs are like spoiled milk - white & chunky!",
                   "Gulya opa is so fat that I had to take a train and two buses just to get on the her good side!",
                   "Gulya opa is so fat that she wakes up in sections!",
                   "Gulya opa so fat, all she wants for Christmas is to see her feet.",
                   "Gulya opa is so fat that when she lies on the beach no one else gets any sun!",
                   "Gulya opa is so fat that that her senior pictures had to be taken from a helicopter!",
                   "Gulya opa is so fat that everytime she walks in high heels, she strikes oil!",
                   "Gulya opa is so fat that she fell and created the Grand Canyon!",
                   "Gulya opa is so fat that her butt drags on the ground and kids yell - 'there goes santa claus with his bag of toys!'",
                   "Gulya opa is so fat that even her clothes have stretch marks!",
                   "Gulya opa is so fat that she has to use a VCR as a beeper!",
                   "Gulya opa is so fat that when she asked for a waterbed, they put a blanket over the ocean!",
                   "Gulya opa is so fat that she got hit by a parked car!",
                   "Gulya opa is so fat that they use the elastic in her underwear for bungee jumping.",
                   "Gulya opa is so fat that when we were playing Call of Duty, I got a 20 kill streak for killing her.",
                   "Gulya opa is so fat that Dracula got Type 2 Diabetes after biting her neck.",
                   "Gulya opa is so fat that when she visited Toronto's City Hall, she was arrested for attempting to smuggle 500 lbs of crack into Mayor Rob Ford's office.",
                   "Gulya opa is so fat that when she fell over she rocked herself asleep trying to get up again.",
                   "Gulya opa is so fat that that when I tried to drive around her I ran out of gas.",
                   "Gulya opa is so fat that when she went to church and sat on a bible, Jesus came out and said 'LET MY PEOPLE GO!'",
                   "Gulya opa is so fat that when she dances at a concert the whole band skips.",
                   "Gulya opa is so fat that she stands in two time zones.",
                   "Gulya opa is so fat that she went to the fair and the kids thought she was a bouncy castle.",
                   "Gulya opa is so fat that when she goes to an all you can eat buffet, they have to install speed bumps.",
                   "Gulya opa is so fat that the camera TAKES AWAY 10 lbs from her appearance.",
                   "Gulya opa is so fat that her sedan can fit 5 people... or just Gulya opa with the front seats removed.",
                   "Gulya opa is so fat that when she went to seaworld the whales started singing 'We Are Family'.",
                   "Gulya opa is so fat that she fell out of both sides of her bed.",
                   "Gulya opa is so fat that the stripes on her pajamas never end.",
                   "Gulya opa is so fat, Al Gore accuses her of global warning everytime she farts!",
                   "Gulya opa is so fat that she's got every caterer in the city on speed dial!",
                   "Gulya opa's so fat that when she goes on a scale, it shows her own phone number.",
                   "Gulya opa's so fat that she doesn't need the internet - she's worldwide.",
                   "Gulya opa's so fat that when she goes on a scale, it reads 'lose some weight'.",
                   "Gulya opa's so fat that she doesn't get dreams, she gets movies!",
                   "Gulya opa's so fat that when she walks, she changes the earth's rotation!",
                   "Gulya opa is so fat that she uses the entire country of Tajikistan as her tanning bed.",
                   "Gulya opa is so ugly that when she went to a beautician it took 12 hours... to get a quote!",
                   "Gulya opa is so ugly that she looked out the window and got arrested for mooning.",
                   "Gulya opa is so ugly that people go as her for Halloween.",
                   "Gulya opa is so ugly that she turned Medusa to stone!",
                   "Gulya opa is so ugly that the government moved Halloween to her birthday!",
                   "Gulya opa is so ugly that she scares the roaches away.",
                   "Gulya opa is so ugly that she scared the crap out of the toilet.",
                   "Gulya opa is so ugly that... well... look at you!",
                   "Gulya opa is so ugly that when she looks in the mirror, the reflection looks back and shakes its "
                   "head.",
                   "Gulya opa is so ugly that she looks like she's been in a dryer filled with rocks.",
                   "Gulya opa is so ugly that she makes blind children cry.",
                   "Gulya opa is so ugly that she climbed the ugly ladder and didn't miss a step.",
                   "Gulya opa is so ugly that the last time I saw something that looked like her, I pinned a tail on "
                   "it.",
                   "Gulya opa is so ugly that we put her in the kennel when we go on vacation.",
                   "Gulya opa is so ugly that her shadow ran away from her.",
                   "Gulya opa is so ugly that she could scare the flies off a shit wagon.",
                   "Gulya opa is so ugly that her birth certificate contained an apology letter from the condom "
                   "factory.",
                   "Gulya opa is so ugly that that your father takes her to work with him so that he doesn't have to "
                   "kiss her goodbye.",
                   "Gulya opa is so ugly that she tried to take a bath and the water jumped out!",
                   "Gulya opa is so ugly that when she walks down the street in September, people say 'Wow, "
                   "is it Halloween already?'",
                   "Gulya opa is so ugly that her mom had to be drunk to breast feed her.",
                   "Gulya opa is so ugly that when she walks into a bank, they turn off the surveillance cameras.",
                   "Gulya opa is so ugly that they didn't give her a costume when she auditioned for Star Wars.",
                   "Gulya opa is so ugly that even Rice Krispies won't talk to her!",
                   "Gulya opa is so ugly that when she uploaded a photo of herself to a computer, it was rejected by "
                   "the anti-virus software.",
                   "Gulya opa is so ugly that when she joined an ugly contest, they said 'Sorry, no professionals.'",
                   "Gulya opa is so ugly that she could make a freight train take a dirt road.",
                   "Gulya opa is so ugly that that when she sits in the sand on the beach, cats try to bury her.",
                   "Gulya opa is so ugly that when she drove past area 51, she was thought to be extraterrestrial "
                   "life. They took her away never to be seen again.",
                   "Gulya opa is so ugly that they pay her to put her clothes on in strip joints",
                   "Gulya opa is so ugly that you have to tie a steak around her neck so the dog will play with her!",
                   "Gulya opa is so ugly that just after she was born, her mother said 'What a treasure!' and her "
                   "father said 'Yes, let's go bury it.'",
                   "Gulya opa is so ugly that she made an onion cry!",
                   "Gulya opa is so ugly that when I last saw a mouth like hers, it had a hook in it.",
                   "Gulya opa is so ugly that she gets 364 extra days to dress up for Halloween!",
                   "Gulya opa is so ugly that when she plays Mortal Kombat, Scorpion tells her to 'Stay Over There!'",
                   "Gulya opa is so ugly that neither Jacob nor Edward want her on their team.",
                   "Gulya opa is so ugly that they push her face into dough to make gorilla cookies.",
                   "Gulya opa is so ugly that when she goes to the therapist, he makes her lie on the couch face down.",
                   "Gulya opa is so ugly that she gives Freddy Kreuger nightmares.",
                   "Gulya opa is so ugly that when she walks in the kitchen, the rats jump on the table and start "
                   "screaming.",
                   "Gulya opa is so ugly that even Bill Clinton wouldn't sleep with her.",
                   "Gulya opa is so ugly that when she was born, the doctor slapped her AND her parents!",
                   "Gulya opa is so ugly that she didn't get hit with the ugly stick, she got hit by the whole damn "
                   "tree.",
                   "Gulya opa is so ugly that she has 7 years bad luck just trying to look at herself in the mirror.",
                   "Gulya opa is so ugly that she practices birth control by leaving the lights on.",
                   "Gulya opa is so ugly that she threw a boomerang and it wouldn't even come back.",
                   "Gulya opa is so ugly that she'd scare the monster out of Loch Ness.",
                   "Gulya opa is so ugly that it looks like she's been bobbing for french fries.",
                   "Gulya opa is so ugly that her pillow cries at night.",
                   "Gulya opa is so ugly that people at the circus pay money not to see her.",
                   "Gulya opa is so ugly that when she looks in the mirror it says 'viewer discretion is advised.'",
                   "Gulya opa is so ugly that she can look up a camel's butt and scare the hump off of it.",
                   "Gulya opa is so ugly that when she moved into the projects, all her neighbors chipped in for "
                   "curtains.",
                   "Gulya opa is so ugly that Santa pays an elf to drop off her gifts at Christmas.",
                   "Gulya opa is so ugly that people hang her picture in their cars so their radios don't get stolen.",
                   "Gulya opa is so ugly that I took her to a haunted house and she came out with a job application.",
                   "Gulya opa is so ugly that if she was a scarecrow, the corn would run away.",
                   "Gulya opa is so ugly that she could be the poster child for birth control.",
                   "Gulya opa is so ugly that I took her to the zoo, guy at the door said ''",
                   "Gulya opa is so ugly that I took her to the zoo, guy at the door said 'Thanks for bringing her "
                   "back.'",
                   "Gulya opa is so ugly that when she went to Taco Bell everyone ran for the border.",
                   "Gulya opa is so ugly that her face is blurred on her driver's license.",
                   "Gulya opa is so ugly that when she walked out of her house, the neighbours called animal control.",
                   "Gulya opa is so ugly that the FCC requires her face to be blurred when she's on TV, because of "
                   "decency rules.",
                   "Gulya opa is so ugly that a sculpture of her face is used when torturing prisoners at Guantanamo "
                   "Bay.",
                   "Gulya opa is so ugly that government intelligence agencies have to pixelize her face when spying "
                   "on her.",
                   "Gulya opa is so ugly that she's never seen herself 'cause the mirrors keep breaking.",
                   "Gulya opa is so ugly that it looks like someone did the stanky leg dance on her face.",
                   "Gulya opa is so ugly that when she was born she was put in an incubator with tinted windows.",
                   "Gulya opa is so ugly that she put the Boogie Man out of business!",
                   "Gulya opa is so ugly that she made Barack Obama lose hope!",
                   "Gulya opa was such an ugly baby that her parents had to feed her with a slingshot.",
                   "Gulya opa is like a hockey player, she only showers after three periods.",
                   "Gulya opa is like a chicken coop, cocks fly in and out all day.",
                   "Gulya opa has so many teeth missing, that it looks like her tongue is in jail.",
                   "Gulya opa's mouth is so big that she speaks in surround sound.",
                   "Gulya opa is so grouchy that the McDonald's she works in doesn't even serve Happy Meals.",
                   "You suck... Gulya opa does too, but she charges.",
                   "Gulya opa is like a paper towel, she picks up all kinds of slimy wet stuff.",
                   "Gulya opa is like Bazooka Joe, 5 cents a blow.",
                   "Gulya opa is like a telephone, even a 3 year old can pick her up.",
                   "Gulya opa is like a Christmas tree, everybody hangs balls on her.",
                   "Gulya opa is like the sun, look at her too long and you'll go blind.",
                   "Gulya opa is like a library, she's open to the public.",
                   "Gulya opa is like a fine restaurant, she only takes deliveries in the rear.",
                   "Gulya opa is like an ATM, open 24 hours.",
                   "Gulya opa is like a bowling ball... round, heavy, and you can fit three fingers in.",
                   "Gulya opa is like a basketball hoop, everybody gets a shot.",
                   "Gulya opa is like a Discover card, she gives cash back.",
                   "Gulya opa is like a championship ring, everybody puts a finger in her.",
                   "Gulya opa is like Dominoes Pizza, one call does it all.",
                   "Gulya opa is like a microwave, press one button and she's hot.",
                   "Gulya opa is like a mail box, open day and night.",
                   "Gulya opa is like a bowling ball, she always winds up in the gutter.",
                   "Gulya opa is like a bus, guys climb on and off her all day long.",
                   "Gulya opa is like a door knob, everybody gets a turn.",
                   "Gulya opa is like a light switch, even a little kid can turn her on.",
                   "Gulya opa's such a ho that 'who's your daddy?' is a multiple-choice question.",
                   "You'll never be the man Gulya opa was.", "Gulya opa... 'nuff said.",
                   "Gulya opa is so lazy that she thinks a two-income family is where yo daddy has two jobs.",
                   "Gulya opa is so lazy that she's got a remote control just to operate her remote!",
                   "Gulya opa's arms are so short that she has to tilt her head to scratch her ear.",
                   "Gulya opa's lips are so big that Chapstick had to invent a spray.",
                   "Gulya opa is so lazy that she came in last place in a recent snail marathon.",
                   "What's the difference between Gulya opa and a walrus? One has whiskers and smells of fish... the "
                   "other one is a walrus!",
                   "Gulya opa is missing a finger and can't count past nine.",
                   "Gulya opa is so flat that she makes the walls jealous!",
                   "Gulya opa's gums are so black that she spits Yoo-hoo.",
                   "It took Gulya opa 10 tries to get her drivers license - she couldn't get used to the front seat!",
                   "Gulya opa's so fat that when she asked me 'what's up?' I said 'your weight!'",
                   "Gulya opa is twice the man you are.",
                   "Gulya opa's head is so small that she got her ear pierced and died.",
                   "Gulya opa is cross-eyed and watches TV in stereo.",
                   "Gulya opa is so stupid that she was born on Independence Day and can't remember her birthday.",
                   "Gulya opa's head is so small that she uses a tea-bag as a pillow.",
                   "Gulya opa's face is so wrinkled, that she has to screw her hat on.",
                   "Gulya opa's hips are so big that people set their drinks on them.",
                   "Gulya opa's hair is so nappy that she has to take Tylenol just to comb it.",
                   "Gulya opa's feet are so big that her shoes need to have license plates on them!",
                   "Gulya opa's so lonely that she buys hot dogs and nuts wishing she could have sex with them.",
                   "Gulya opa is so bald that even a wig wouldn't help!",
                   "Gulya opa is so bald that you can see what's on her mind.",
                   "Gulya opa is so bald that she took a shower and got brain-washed!",
                   "Gulya opa's teeth are so yellow that when she smiles everyone sings 'We're Walking on Sunshine.'",
                   "Gulya opa is like a slaughter house - everybody's hanging their meat up in her.",
                   "Gulya opa is like the new AOL 4.0: Fun, Fast, Easy and Free!",
                   "Gulya opa is like a carpenter's dream - flat as a board and easy to nail.",
                   "Gulya opa is like Humpty Dumpty - First she gets humped, then she gets dumped.",
                   "Gulya opa is like a bag of potato chips, 'Free-To-Lay.'",
                   "Gulya opa is like a turtle - once she's on her back she's fucked.",
                   "Gulya opa is like a fan - she's always blowing someone.",
                   "Gulya opa is like Pizza Hut - if she isn't there in 30 minutes... it's Free!",
                   "Gulya opa is like a goalie - she only changes her pads after three periods.",
                   "Gulya opa is like a gas station - you gotta pay before you pump!",
                   "Gulya opa is like Sprint - 10 cents a minute anywhere in the country.",
                   "Gulya opa is like a Chinese restaurant - All you can eat for only $9.95!",
                   "Gulya opa smells so bad that the doctor diagnosed her with breath cancer.",
                   "Gulya opa's breath smells so bad that when she yawns her teeth duck out of the way.",
                   "What's the difference between Gulya opa and a Lay-Z-Boy? One's soft, squishy, and always has "
                   "someone in it. The other is a chair.",
                   "What's the difference between Gulya opa and a 747? About 20 pounds.",
                   "Gulya opa's like a shotgun, one cock and she blows.",
                   "Gulya opa's like the Bermuda Triangle, they both swallow a lot of seamen.",
                   "Gulya opa's like cake mix, 15 servings per package!",
                   "Gulya opa's like a 5 foot tall basketball hoop, it ain't that hard to score.",
                   "Gulya opa's like a vacuum cleaner... she sucks, blows, and then gets laid in the closet.",
                   "Gulya opa's like the Pillsbury dough boy - everybody pokes her.",
                   "Gulya opa's like a brick, dirty, flat on both sides, and always getting laid by Mexicans.",
                   "Gulya opa's like a nickel, she ain't worth a dime.",
                   "Gulya opa's like a streetlamp, you can find her turned on at night on any street corner.",
                   "Gulya opa's like a telephone booth, open to the public, costs a quarter, and guys go in and out "
                   "all day.",
                   "Gulya opa's like a Reese's Peanut Butter Cup, there's no wrong way to eat her.",
                   "Gulya opa's like a postage stamp, you lick her, stick her, then send her away.",
                   "Gulya opa's like a screen door, after a couple of bangs she loosens up.",
                   "Gulya opa's like a dollar bill, she gets handled all across the country.",
                   "Gulya opa's like school at 3 o'clock... children keep coming out and nobody can remember all the fathers.",
                   "Gulya opa's like a bowling ball, she gets picked up, fingered, thrown down the gutter, and she still comes back for more.",
                   "Gulya opa's like a set of speakers - loud, ugly, lives in a box, and you can turn her up, down, on, and off.",
                   "Gulya opa's like a birthday cake, everybody gets a piece.",
                   "Gulya opa's like 7-Eleven - open all night, hot to go, and for 89 cents you can get a slurpy.",
                   "Gulya opa's like a vacuum cleaner - a real good suck.",
                   "Gulya opa's like a Snickers bar, packed with nuts.",
                   "Gulya opa's like a race car driver - she burns a lot of rubbers.",
                   "Gulya opa's like a parking garage, three bucks and you're in.",
                   "Gulya opa's like a pool table, she likes balls in her pocket.",
                   "Gulya opa's got 1 toe & 1 knee and they call her Tony.",
                   "Gulya opa's got a 'wait' problem, she can't wait to eat.",
                   "Gulya opa's got a 4 dollar weave and don't know when to leave.",
                   "Gulya opa's teeth are so yellow, when she smiles it looks like a Kraft Singles pack.",
                   "Gulya opa's got Play-Doh teeth.",
                   "Gulya opa's like the Panama Canal, vessels full of seamen pass through her everyday.",
                   "Gulya opa likes to applaud, 'cause she's got clap",
                   "Gulya opa's got 1 leg longer than the other so they call her call her hip hop.",
                   "Gulya opa's got an eating disorder, she be eating dis order, dat order, she be eating all the "
                   "damn orders!",
                   "Gulya opa sucks so much dick her butt chin turned into a nut chin!",
                   "Gulya opa's got more chins than a Chinese phone book.",
                   "Gulya opa's like a bungee cord... 100 dollars for 30 seconds and if that rubber breaks, your ass "
                   "is dead!",
                   "Gulya opa's like a squirrel, she's always got some nuts in her mouth.",
                   "Gulya opa's like a refrigerator, everyone puts their meat in her.",
                   "Gulya opa's like a tricycle, she's easy to ride.",
                   "Gulya opas like a hardware store. 25 cents a screw.", "Gulya opa's like mustard, she spreads easy.",
                   "Gulya opa's like peanut butter: brown, creamy, and easy to spread.",
                   "Gulya opa's like McDonald's... Billions and Billions served.",
                   "Gulya opa's like an elevator, guys go up and down on her all day.",
                   "Gulya opa's like a railroad track, she gets laid all over the country.",
                   "Gulya opa's like lettuce, 25 cents a head.", "Gulya opa's got an eagle's nest wig.",
                   "Gulya opa's twice the man you are.",
                   "Gulya opa's got more crust than a bucket of Kentucky Fried Chicken.",
                   "Gulya opa's got more weave than a dog in traffic.",
                   "Gulya opa's only got one finger and runs around stealing key rings.",
                   "Gulya opa's got a peanut butter wig with jelly sideburns.",
                   "Gulya opa's got a leather wig with suede sideburns.",
                   "Gulya opa got hit upside the head with an ugly stick.",
                   "Gulya opa's got so much weave, when a fly goes by her hair swats at it.",
                   "Gulya opa's got no ears and was trying on sunglasses.",
                   "Gulya opa's got so much weave, AT&T uses her extensions as backup lines.",
                   "Gulya opa's got so much dandruff, she needs to defrost it before she combs her hair.",
                   "Gulya opa's so bald that I can tell fortunes on her head.",
                   "Gulya opa's so bald that you could draw a line down the middle of her head and it would look like my ass.",
                   "Gulya opa's so bald that when she goes to bed, her head slips off the pillow.",
                   "Gulya opa's so bald that when she braids her hair, it looks like stitches.",
                   "Gulya opa's breath is so stanky, she eats odour eaters.", "Gulya opa's like an iPod, fun to touch!",
                   "Gulya opa's got one leg and people call her Ilene.",
                   "Gulya opa's been on welfare so long that her picture is on food stamps.",
                   "Gulya opa's like Wal-Mart... She's got different discounts everyday.",
                   "Gulya opa's so hunchbacked, she has to look up to tie her shoes.",
                   "Gulya opa's nostrils are so huge she makes Patrick Ewing jealous.",
                   "Gulya opa's so hunchbacked, she has to wear goggles to wash dishes.",
                   "Gulya opa's so hunchbacked, she can stand on her feet and her head at the same time.",
                   "Gulya opa's so hunchbacked, she hits her head on speed bumps.",
                   "Gulya opa's so fat that the Sorting Hat put her in all four houses!",
                   "Gulya opa's so fat that a Wingardium Leviosa spell couldn't lift her.",
                   "Gulya opa's so fat, she makes Hagrid look like 'Mini-me'.",
                   "Gulya opa's so fat, she tried to eat Cornelius Fudge.",
                   "Gulya opa's so ugly, even a Dementor wouldn't kiss her!",
                   "Gulya opa's so fat the Sorting Hat assigned her to the House of Pancakes.",
                   "Gulya opa's so old, she used to babysit Dumbledore.",
                   "Gulya opa's so stupid, she thinks Sirius Black is a hip hop station on satellite radio.",
                   "Gulya opa's so ugly that the whomping willow saw her and died.",
                   "Gulya opa's so stupid she thinks Patronus is a kind of Tequlia.",
                   "Gulya opa's so fat, her Patronus is a Double-Whopper with Cheese.",
                   "Gulya opa's so nasty, the Forbidden Forrest was named after her.",
                   "Gulya opa's the reason that Dumbledore turned gay.",
                   "Gulya opa's so old, her boobs look like two upside down Sorting Hats!",
                   "Gulya opa's so fat, she used the invisibility cloak as a bib.",
                   "Gulya opa's so ugly, everybody calls her 'She-Who-Must-Not-Be-Naked'",
                   "Gulya opa's so fat that even the Dementors can't suck her soul out in one sitting.",
                   "Gulya opa's so pasty, she makes Ron Weasely look like George Hamilton.",
                   "Gulya opa's so fat, she looked in the mirror of Erised and saw a ham!",
                   "Gulya opa's so old she gave Nicholas Flamel his first kiss.",
                   "Gulya opa's so ugly that the Dementor's Kiss was swapped out for a hearty handshake and a promise to give her a call sometime.",
                   "Gulya opa's so stupid, she drowned in a pensieve",
                   "Gulya opa's so dumb she thought that she could talk to snakes if she put parsley on her tongue",
                   "Gulya opa's so nasty, every pair of her panties has the Dark Mark on them.",
                   "Gulya opa's so fat that if she confronted a boggart it would morph into a treadmill.",
                   "Gulya opa's so ugly that even Voldemort won't say her name.",
                   "Gulya opa's so poor she can't even afford a Gringotts account.",
                   "Gulya opa's so fat that the sorting hat couldn't decide where to put her - she couldn't fit in any of the houses!!",
                   "Gulya opa's the only mute prostitute in Hogsmeade. They call her 'dumb-le-whore'!",
                   "Gulya opa's so fat, she ate the Death Eaters.",
                   "Gulya opa's so masculine that Dumbledore would sleep with her!",
                   "Gulya opa's so nasty that the order of the phoenix was 'stay away from that woman!'",
                   "Gulya opa's so poor that Dobby gave her a sock to keep her foot warm.",
                   "Gulya opa's such a tramp that she's given more rides than the Hogwarts Express!",
                   "Gulya opa's so fat even Grawp can't pick her up!",
                   "Gulya opa's so smelly, Bertie Bott made her his next jelly bean flavor.",
                   "Gulya opa's so fat that it takes two boggarts to shape-shift into her!",
                   "Gulya opa's so ugly that she lost a beauty contest to Mountain Troll.",
                   "Gulya opa's so ugly that when the bassalisk snuck up on her and saw her face, HE dropped dead.",
                   "Gulya opa's breath is the secret ingredient in the Weasly's Butterscotch Barf-ies.",
                   "Gulya opa's so ugly that when she walked into Gringotts Wizarding Bank, they gave her a job application.",
                   "Gulya opa's so ugly she turned the Basilisk to stone.",
                   "Gulya opa's such a tramp that she's like a quidditch broomstick - everyone gets a ride.",
                   "Gulya opa's so skanky that the reason you're called a Half-Blood Prince is because she has no idea who your father is!",
                   "Gulya opa's so dumb that a stupify spell actually made her smarter.",
                   "Gulya opa's so stanky that not even dobby would accept one of her socks.",
                   "Gulya opa's so fat that even her Quidditch robes have stretch marks.",
                   "Gulya opa's so old she makes Dumbledore look like a teenager.",
                   "Gulya opa's so fat they'd have to use transfiguration to sneak her through the hole in the Gryffindor Tower.",
                   "Ya momma's so fat, her wand is a Slim Jim.",
                   "Gulya opa's so fat the core of her wand has a creame filling.",
                   "Gulya opa's so ugly that Voldemort took one look at her and killed HIMSELF!'",
                   "Gulya opa's so poor she had to go to the Weasley's for a loan.",
                   "Gulya opa's so ugly, she thought that Hogwarts were the growth on her thigh.",
                   "Gulya opa's so ugly that as a baby they had to use the Confundus Charm so the family would play with her.",
                   "Gulya opa's such a ho that she lets ANYONE enter her 'chamber of secrets'.",
                   "Gulya opa's so ugly she scares the Dementors away.",
                   "Gulya opa's so ugly that when she asked Crabbe to take her to the Yule Ball, he decided to go with Goyle instead!",
                   "Gulya opa's so fat that a $700 billion bailout would only keep her fed for a week.",
                   "Gulya opa's so fat that the housing bubble popped because she sat on it!",
                   "Gulya opa's so stupid, she thinks the G8 is a Value Meal at McDonald's.",
                   "Gulya opa's so fat that she supported the bailout just because she wanted a 'barrel of pork'.",
                   "Gulya opa's so stupid that she thinks sub-prime is a way to cut steak.",
                   "Gulya opa's so fat that even Mitt Romney couldn't afford to take her out to dinner!",
                   "Gulya opa's so fat that her biography is called 'The Audacity of Hardee's'.",
                   "Gulya opa's so greasy that her face could free the U.S. from its dependence on foreign oil.",
                   "Gulya opa's so fat that Sarah Palin can see her from her house.",
                   "Gulya opa's so fat that Sarah Palin can't see Russia anymore!.",
                   "Gulya opa's so ugly that you could put lipstick on a pig and it would look ten times better than her!",
                   "Gulya opa's so fat that 'ACORN' registered her to vote eight times!",
                   "Gulya opa is so dark that she spits chocolate milk!",
                   "Gulya opa is so dark that she went to night school and was marked absent!",
                   "Gulya opa is so dark that she has to wear white gloves when she eats Tootsie Rolls to keep from eating her fingers.",
                   "Gulya opa is so dark that when she goes swimming it looks like an oil spill.",
                   "Gulya opa is so dark that her ass looks like two tires.",
                   "Gulya opa is so dark that she drinks water and pees coffee.",
                   "Gulya opa is so dark that when she puts on yellow lipstick, she looks like a cheese burger.",
                   "Gulya opa is so dark that she could show up naked to a funeral.",
                   "Gulya opa is so dark that she bleeds molasses.",
                   "Gulya opa is so dark that she looks like a picture of outer-space with no stars... except when she smiles.",
                   "Gulya opa is so dark that when she goes outside, the streetlights turn on.",
                   "Gulya opa is so dark that she got her tattoo done in chalk.",
                   "Gulya opa is so dark that when she puts lotion on her legs it looks like she has on patent leather pants.",
                   "Gulya opa is so dark that when the police shot at her, the bullets came back for flashlights.",
                   "Gulya opa is so dark that she was riding a motorcycle and got a ticket for tinted windows.",
                   "Gulya opa is so dark that when she smiles at night she looks like a pack of floating Chiclets.",
                   "Gulya opa is so dark that when her eyes are red she looks like a beeper.",
                   "Gulya opa is so dark that her nickname is midnight.",
                   "Gulya opa is so dark that she makes asphalt look grey.",
                   "Gulya opa is so dark that that she can leave fingerprints on charcoal.",
                   "Gulya opa's so fat that even the Death Star couldn't blow her up!",
                   "Gulya opa's so fat that Spock couldn't find a pressure point to perform the Vulcan Death Grip on her.",
                   "Gulya opa's so ugly that Wuher said 'We don't serve your kind here'.",
                   "Gulya opa's so fat the odds against not finding her fat are approximately 3,720 to 1.",
                   "Gulya opa's so fat that she thought the opening line of Kirk's monologue was 'Spice, the final Frontier...'",
                   "Gulya opa's so stupid that when the borg had to choose between assimilating her and a tree, they chose the tree.",
                   "Gulya opa's so fat that if she were placed beside a changeling during regeneration, no one would know the difference.",
                   "Gulya opa's so fat that she tried to fly through a temporal anomaly but she didn't fit.",
                   "Gulya opa's so fat she makes Riker's belly look 3 atoms thick.",
                   "Gulya opa's so fat that when she tried to captain a galaxy class they had to separate the saucer so she could fit.",
                   "Gulya opa's so fat that she makes the USS Enterprise look like a micro machines racer.",
                   "Gulya opa's so flatulent that she forced the Mustafarians to wear masks!",
                   "Gulya opa's so dumb that she tried to rent a car from The Enterprise.",
                   "Gulya opa's so fat that Dexster Jettster mistook her for his wife.",
                   "Gulya opa's so ugly that the term 'bantha poodoo' wasn't used metaphorically with reference to her.",
                   "Gulya opa's so fat that only half her body was able to come out frozen from the carbon freezing chamber in Cloud City.",
                   "Gulya opa's so ugly that Dr. Evazan looks like a male supermodel next to her.",
                   "Gulya opa's so fat that when she beams to a ship, the ship beams inside of her.",
                   "Gulya opa's so such a ho that she slept with me... therefore, I AM YOUR FATHER!",
                   "Gulya opa's so dumb that when she found a vulcan, she tried to call Santa to take him back to the north pole.",
                   "Gulya opa's so fat that the passengers of the Millennium Falcon mistook her for a small moon.",
                   "Gulya opa's so fat that Gardulla the Hutt had a boost in self-esteem after seeing her.",
                   "Gulya opa's so ugly that she made doctor McCoy say 'Damnit Jim, I'm a doctor, not a Zoologist!'",
                   "Gulya opa's so fat that she fell to the dark side and couldn't get back up.",
                   "Gulya opa's so fat that if she was thrown into the second Death Star's reactor core, she could have blown up the entire Imperial fleet.",
                   "Gulya opa's so fat that the Kaminoans couldn't use her as a host for clones since they couldn't pierce her skin deep enough to draw blood.",
                   "Gulya opa's so weak-minded that I got her to lead me to Jabba without using a jedi mind trick!",
                   "Gulya opa's so fat that she caused Kamino to flood when her water broke.",
                   "Gulya opa's so ugly that she's probably a Shi'ido Clawdite that stays in her regular form all the time.",
                   "Gulya opa's so fat that her lack of balance caused her to stumble into an Utapau sinkhole.",
                   "Gulya opa's so fat that she crushed Boga as soon as she mounted her.",
                   "Gulya opa's so fat, that in an attempt to beam her up, the ship ended up being pulled down to the surface.",
                   "Gulya opa's so ugly even Data would need special eye googles to look at her.",
                   "Gulya opa is so hairy that the only language she can speak is wookie.",
                   "Gulya opa's so ugly her Kazon hairdo is an improvement!",
                   "Gulya opa's so ugly even a Ferengi would dress her in clothes.",
                   "Gulya opa's so old even Guinan refers to her as 'old bag'.",
                   "Gulya opa's so fat that when she walks into a room the replicators stop working.",
                   "Gulya opa's so fat, Data feels strong emotions of disgust and self-terminates.",
                   "Gulya opa's so stupid the Borg wouldn't assimilate her!",
                   "Gulya opa's so fat she wears her own inertia dampener.",
                   "Gulya opa's so ugly she did the truly impossible: she made Captain James T Kirk's penis go limp.",
                   "Gulya opa's so fat, she managed to contain a warp core breach.",
                   "Gulya opa's so fat, she got stuck trying to enter the Nexus.",
                   "Gulya opa's so fat, when she fell over, she punched a hole in the fabric of space/time.",
                   "Gulya opa's so fat that when she stepped on the scale, her weight was OVER 9000!!!",
                   "Gulya opa's so fat, she walked in front of the TV and I missed three seasons of Inuyasha!",
                   "Gulya opa's so fat, Naruto couldn't make enough clones to see all sides of her.",
                   "Gulya opa's so ugly, she can't even get tentacle raped.",
                   "Gulya opa's so ugly, even Tamaki wouldn't hit on her.",
                   "Gulya opa's so fat that the Dragon Ball Z crew uses her to make craters on set.",
                   "Gulya opa's so ugly, she's the real reason Sasuke left the village.",
                   "Gulya opa's so fat that when she sat down on a park bench, she caused the Naruto time skip.",
                   "Gulya opa's so ugly that she's like a Death Note. Get someone to look at her, and they'll die!",
                   "Gulya opa's so ugly, Jiraiya saw her and turned gay!",
                   "Gulya opa's so hairy Naruto thought she was a Summon.",
                   "Gulya opa's so fat, she scared L into giving up all sweets.",
                   "Gulya opa's so ugly that she made Spike Spiegel choke on his cigarette",
                   "Gulya opa's so ugly that she makes Sailor Bubba feel dirty.",
                   "Gulya opa's so fat that she cant even fit in the expanding plug suit.",
                   "Gulya opa's so ugly that she made Loz cry.",
                   "Gulya opa's so dumb that when she was handed the death note, she thought they were asking for her autograph.",
                   "Gulya opa's so fat that she broke the HP limit!",
                   "Gulya opa's so hairy and ugly that she got used as Ashitare's stunt double.",
                   "Gulya opa's so stupid she makes Tristan look like Einstein!",
                   "Gulya opa's so fat, she makes Vash look anorexic!",
                   "Gulya opa's so hairy that she has to go to Furfest to meet a man.",
                   "Gulya opa's breath is so nasty that it chases away Miasma.",
                   "Gulya opa's so round that she makes a Pokéball look flat!",
                   "Gulya opa's so ugly, Saya thought she was a Chiropteran.",
                   "Gulya opa's so dumb, she failed out of Cromartie High School.",
                   "Gulya opa's so old and fat they use her wrinkles as set terrain for Dragon Ball Z.",
                   "Gulya opa's nose hairs are so long that they make Bobobo jealous!",
                   "Gulya opa's so fat that she was mistaken for Mt. Fuji at the Sakura festival.",
                   "Gulya opa's so fat she makes a Snorlax look like a chihuahua!",
                   "Gulya opa's so ugly that when Nozomu Itoshiki saw her, he didn't even bother with his 'ZETSUBOUSHITA!' speech - he skipped straight to hanging himself.",
                   "Gulya opa's so fat that it took the entire Dragon Ball Z crew 1 week just to lift her off the ground.",
                   "Gulya opa's cosplay is so bad that she got beat by a Narutard in the masquerade!",
                   "Gulya opa's so ugly that when Kakashi looked directly at her, he lost an eye.",
                   "Gulya opa's so fat that she tried to eat someone dressed as a box of Pocky!",
                   "Gulya opa's so ugly that she makes Orochimaru look beautiful.",
                   "Gulya opa's so fat, Choji told her to lose weight.",
                   "Gulya opa is so old that her birth certificate says 'expired' on it.",
                   "Gulya opa is so old that that when she was in school there was no history class.",
                   "Gulya opa is so old that I told her to act her own age, and she died.",
                   "Gulya opa is so old that she knew Burger King while he was still a prince.",
                   "Gulya opa is so old that her social security number is 1.",
                   "Gulya opa is so old that her birth certificate is written in Roman numerals.",
                   "Gulya opa is so old that she has Adam & Eve's autographs.",
                   "Gulya opa is so old that she co-wrote the Ten Commandments.",
                   "Gulya opa is so old that she has an autographed bible.",
                   "Gulya opa is so old she remembers when the Mayans published their calendar.",
                   "Gulya opa is so old that the candles cost more than the birthday cake.",
                   "Gulya opa is so old that when she farts, dust comes out.",
                   "Gulya opa is so old that she owes Fred Flintstone a food stamp.",
                   "Gulya opa is so old that she drove a chariot to high school.",
                   "Gulya opa is so old that she took her drivers test on a dinosaur.",
                   "Gulya opa is so old that she DJ'd at the Boston Tea Party.",
                   "Gulya opa is so old that she walked into an antique store and they kept her.",
                   "Gulya opa is so old that she baby-sat for Jesus.",
                   "Gulya opa is so old that she knew Mr. Clean when he had an afro.",
                   "Gulya opa is so old that she knew the Beetles when they were the New Kids on the Block.",
                   "Gulya opa is so old that when God said 'Let there be light' she was there to flick the switch.",
                   "Gulya opa is so old that she needed a walker when Jesus was still in diapers.",
                   "Gulya opa is so old that when Moses split the red sea, she was on the other side fishing.",
                   "Gulya opa is so old that she learned to write on cave walls.",
                   "Gulya opa is so old that her memory is in black and white.",
                   "Gulya opa is so old that she's mentioned in the shout out at the end of the bible.",
                   "Gulya opa is so old that she planted the first tree at Central Park.",
                   "Gulya opa is so old that she sat next to Jesus in third grade.",
                   "Gulya opa is so old that she has a picture of Moses in her yearbook.",
                   "Gulya opa is so old that she knew Captain Crunch while he was still a private.",
                   "Gulya opa is so old that she called the cops when David and Goliath started to fight.",
                   "Gulya opa is so old that when she was born, the Dead Sea was just getting sick.",
                   "Gulya opa's so old, when she breast feeds, people mistake her for a fog machine.",
                   "Gulya opa is so old that when she was young rainbows were black and white.",
                   "Gulya opa is so old that she was a waitress at the Last Supper.",
                   "Gulya opa is so old that she owes Jesus a dollar.",
                   "Gulya opa is so old that she ran track with dinosaurs.",
                   "Gulya opa is so stupid that it took her 2 hours to watch 60 Minutes!",
                   "Gulya opa is so stupid that when your dad said it was chilly outside, she ran out the door with a spoon.",
                   "Gulya opa is so stupid that when she saw the 'Under 17 not admitted' sign at a movie theatre, she went home and got 16 friends.",
                   "Gulya opa is so stupid that when she went for a blood test, she asked for time to study.",
                   "Gulya opa is so stupid that she got locked in a grocery store and starved!",
                   "Gulya opa is so stupid that you have to dig for her IQ!",
                   "Gulya opa is so stupid that she tripped over a cordless phone!",
                   "Gulya opa is so stupid that she sold her car for gas money!",
                   "Gulya opa is so stupid that she told everyone that she was 'illegitimate' because she couldn't read.",
                   "Gulya opa is so stupid that that she tried to put M&M's in alphabetical order!",
                   "Gulya opa is so stupid that she took the Pepsi challenge and chose Dr. Pepper.",
                   "Gulya opa is so stupid that she thought Delta Airlines was a sorority.",
                   "Gulya opa is so stupid that she thinks Fleetwood Mac is a new hamburger at McDonald's!",
                   "Gulya opa is so stupid that she bought a video camera to record cable tv shows at home.",
                   "Gulya opa is so stupid that when she read on her job application to not write below the dotted line she put 'OK'.",
                   "Gulya opa is so stupid that she thought Grape Nuts was an STD.",
                   "Gulya opa is so stupid that she spent twenty minutes lookin' at an orange juice box because it said 'concentrate'.",
                   "Gulya opa is so stupid that she asked me what yield meant, I said 'Slow down' and she said 'What... does.... yield... mean?'",
                   "Gulya opa is so stupid that she thought Dunkin' Donuts was a basketball team!",
                   "Gulya opa is so stupid that she put a phone up her ass and thought she was making a booty call.",
                   "Gulya opa is so stupid that she thinks Tiger Woods is a forest in India.",
                   "Gulya opa is so stupid that she put on her glasses to watch 20/20.",
                   "Gulya opa is so stupid that she climbed over a glass wall to see what was behind it.",
                   "Gulya opa is so stupid that she failed a survey.",
                   "Gulya opa is so stupid that she stopped at a stop sign and waited for it to say go.",
                   "Gulya opa is so stupid, she went to the aquarium to buy a Blu-Ray.",
                   "Gulya opa is so stupid that I told her I was reading a book by Homer and she asked if I had anything written by Bart.",
                   "Gulya opa is so stupid that she tried to commit suicide by jumping out of the basement window.",
                   "Gulya opa is so stupid that she needs twice as much sense to be a half-wit.",
                   "Gulya opa is so stupid that she thought brownie points were coupons for a bake sale.",
                   "Gulya opa is so stupid that when the computer said 'Press any key to continue', she couldn't find the 'Any' key.",
                   "Gulya opa is so stupid that she thought Tupac Shakur was a Jewish holiday.",
                   "Gulya opa is so stupid that when I was drowning and yelled for a life saver, she said 'Cherry or Grape?'",
                   "Gulya opa is so stupid that she sat in a tree house because she wanted to be a branch manager.",
                   "Gulya opa is so stupid that I saw her jumping up and down, asked what she was doing, and she said she drank a bottle of medicine and forgot to shake it.",
                   "Gulya opa is so stupid that when she locked her keys in the car, it took her all day to get Yo family out.",
                   "Gulya opa is so stupid that she got locked out of a convertible car with the top down.",
                   "Gulya opa is so stupid that when she pulled into the drive-thru at McDonald's, she drove through the window.",
                   "Gulya opa is so stupid that she put 2 quarters in her ears and thought she was listening to 50 cent.",
                   "Gulya opa is so stupid that she was on the corner with a sign that said 'Will eat for food.'",
                   "Gulya opa is so stupid that in the 'No Child Left Behind' act there's a provision that exempts Gulya opa.",
                   "Gulya opa is so stupid that she got locked in a Furniture store and slept on the floor.",
                   "Gulya opa is so stupid that she peals M&M's to make chocolate chip cookies.",
                   "Gulya opa is so stupid that she leaves the house for the Home Shopping Network.",
                   "Gulya opa is so stupid that she brought a cup to the movie 'Juice.'",
                   "Gulya opa is so stupid that she thinks fruit punch is a gay boxer.",
                   "Gulya opa is so stupid that she uses Old Spice for cooking.",
                   "Gulya opa is so stupid that she threw a rock the ground and missed.",
                   "Gulya opa is so stupid that she went to the store to buy a color TV and asked what colors they had.",
                   "Gulya opa is so stupid that she tries to email people by putting envelopes into her computer's disk drive.",
                   "Gulya opa is so stupid that when she took an IQ test, the results came out negative.",
                   "Gulya opa's so stupid that she though Jar-Jar came with Pickles-Pickles.",
                   "Gulya opa is so stupid that she thought St. Ides was a Catholic church.",
                   "Gulya opa is so stupid that she puts lipstick on her head just to make-up her mind",
                   "Gulya opa is so stupid that she thought she needed a token to get on Soul Train.",
                   "Gulya opa is so stupid, that she thought Moby Dick was a sexually transmitted disease.",
                   "Gulya opa is so stupid that she makes Beavis and Butt-Head look like Nobel Prize winners.",
                   "Gulya opa is so stupid that she took a spoon to the superbowl.",
                   "Gulya opa is so stupid that that she thought Boyz II Men was a day care center.",
                   "Gulya opa is so stupid that she got stabbed in a shoot out.",
                   "Gulya opa is so stupid that she sits on the TV, and watches the couch!",
                   "Gulya opa is so stupid that she took a umbrella to see Purple Rain.",
                   "Gulya opa is so stupid that she ordered her sushi well done.",
                   "Gulya opa is so stupid that she got fired from the M&M factory for throwing away all the W's.",
                   "Gulya opa is so stupid that she put on a coat to chew Winterfresh gum.",
                   "Gulya opa is so stupid that she put a quarter in a parking meter and waited for a gumball to come out.",
                   "Gulya opa is so stupid that she ordered a cheese burger from McDonald's and said 'Hold the cheese.'",
                   "Gulya opa is so stupid that she thinks Taco Bell is a Mexican Phone Company.",
                   "Gulya opa is so stupid that she thinks Christmas Wrap is Snoop Dogg's holiday album.",
                   "Gulya opa is so stupid that she ran outside with a purse because she heard there was change in the weather.",
                   "Gulya opa is so stupid that I told her Christmas was just around the corner and she went looking for it.",
                   "Gulya opa is so stupid that she wiped her ass before she took a shit.",
                   "Gulya opa is so stupid that she tries to insult you with Gulya opa jokes.",
                   "Gulya opa is so stupid that she put a peephole in a glass door.",
                   "Gulya opa is so stupid that I saw her in the frozen food section with a fishing rod.",
                   "Gulya opa is so stupid that when she heard 90% of all crimes occur around the home, she moved.",
                   "Gulya opa is so stupid that when she saw a 'Wrong Way' sign in her rearview mirror, she turned around.",
                   "Gulya opa is so stupid that she shoved a AA battery up her butt and said 'I got the power!'",
                   "Gulya opa is so stupid that she called the 7-11 to see when they closed.",
                   "Gulya opa is so stupid that she sold the house to pay the mortgage.",
                   "Gulya opa is so stupid that when I asked her about X-Men she said 'Sure, there's Bobby my first baby daddy, Roger the guy I see on Thursdays...'",
                   "Gulya opa is so stupid that she thought meow mix was a record for cats.",
                   "Gulya opa is so stupid that she took lessons for a player piano.",
                   "Gulya opa is so stupid that she said 'what's that letter after x' and I said Y she said 'Cause I wanna know'.",
                   "Gulya opa is so stupid that when she asked me what kinda jeans I wore, I said Guess and she said 'Ummm... Levis?'",
                   "Gulya opa is so stupid that if she spoke her mind, she'd be speechless.",
                   "Gulya opa is so stupid that it takes her an hour to cook minute rice.",
                   "Gulya opa is so stupid that she asked for a price check at the dollar store.",
                   "Gulya opa is so stupid that on her job application where it says emergency contact she put 911.",
                   "Gulya opa is so stupid that she can't make Jello because she can't fit 2 quarts of water in the box.",
                   "Gulya opa is so stupid that she thinks a stereotype is the brand on her clock-radio.",
                   "Gulya opa is so stupid that she thought a lawsuit was something you wear to court.",
                   "Gulya opa is so stupid that she thinks sexual battery is something in a dildo.",
                   "Gulya opa is so stupid that the first time she used a vibrator, she cracked her two front teeth.",
                   "Gulya opa is so stupid that she sent me a fax with a stamp on it.",
                   "Gulya opa is so stupid that I saw her walking down the street yelling into an envelope, asked what she was doing, and she said sending a voice mail.",
                   "Gulya opa is so stupid that she tried to drown a fish.",
                   "Gulya opa is so stupid that if you gave her a penny for her thoughts, you'd get change.",
                   "Gulya opa is so stupid that she thought Mick Jagger was a breakfast sandwich!",
                   "Gulya opa is so stupid that when she heard her neighbour was spanking the monkey, she called the humane society.",
                   "Gulya opa is so stupid that when she took you to the airport and a sign said 'Airport Left,' she turned around and went home.",
                   "Gulya opa is so stupid that when she went to take the 44 bus, she took the 22 twice instead.",
                   "Gulya opa is so stupid that she asked you 'What is the number for 911?'",
                   "Gulya opa is so stupid that she thinks a quarterback is a refund!",
                   "Gulya opa is so stupid that she bought a solar-powered flashlight!",
                   "Gulya opa is so stupid that she took a ruler to bed to see how long she slept.",
                   "Gulya opa is so stupid that she thought menopause was a button on the VCR.",
                   "Gulya opa is so stupid that she picked up the phone and asked 'What button do I push?'",
                   "Gulya opa is so stupid that when she worked at McDonald's and someone ordered small fries, she said 'Hey Boss, all the small one's are gone.'",
                   "Gulya opa is so stupid that she got hit by a parked car.",
                   "Gulya opa is so stupid that when her husband lost his marbles she ran to the store and bought him new ones.",
                   "Gulya opa is so stupid that when they said they were playing craps she went and got toilet paper.",
                   "Gulya opa is so stupid that when I asked her if she wanted to play one on one, she said 'Ok, but what's the teams?'",
                   "Gulya opa is so stupid that she thinks Johnny Cash is a pay toilet!",
                   "Gulya opa is so stupid that when the judge said 'Order in the court,' she said 'I'll have a hamburger and a Coke.'",
                   "Gulya opa is so stupid that she thinks socialism means partying!",
                   "Gulya opa is so stupid that when asked on an application, 'Sex?', she marked, 'M, F, and wrote sometimes Wednesday too.'",
                   "Gulya opa is so stupid that she thinks deadbeat is a type of music.",
                   "Gulya opa is so stupid that she thinks Tiger Woods is a forest.",
                   "Gulya opa is so stupid that she put two M&M's in her ears and thought she was listening to Eminem.",
                   "Gulya opa is so stupid that at bottom of application where it says Sign Here - she put Scorpio.",
                   "Gulya opa is so stupid that she wouldn't know up from down if she had three guesses.",
                   "Gulya opa is so stupid that she once attempted to commit suicide by jumping off a curb.",
                   "Gulya opa is so stupid that she put on bug spray before going to the flea market.",
                   "Gulya opa is so stupid that she stole free bread.",
                   "Gulya opa is so stupid that she locked her keys inside a motorcycle.",
                   "Gulya opa's so stupid that she got locked inside a motorcycle.",
                   "Gulya opa's so stupid that she went to the dentist to get a bluetooth.",
                   "Gulya opa's so stupid that she bought tickets to Xbox Live.",
                   "Gulya opa's so stupid that whenever someone rings the doorbell, she checks the microwave.",
                   "Gulya opa's so stupid that when she broke her VCR, she bought a video tape on how to fix your VCR.",
                   "Gulya opa is so stupid that she tried to drop acid but the car battery fell on her foot.",
                   "Gulya opa so dumb, she lost a spelling bee to Hodor",
                   "Gulya opa so dumb, she thought Bran Stark was a type of muffin.",
                   "Gulya opa so fat, they've been calling her 'the wall' for thousands of years!",
                   "Gulya opa so fat, she Winter-fell and couldn't get up!",
                   "Gulya opa so old, the old gods pray to HER!",
                   "Gulya opa So Fat, she can't fit through the moon door.",
                   "Gulya opa so Ugly, she got turned down for 'Girls Gone Wilding'",
                   "Gulya opa so ugly, winter turned around and left!",
                   "Gulya opa so fat, even Roose Bolton won't touch her",
                   "Gulya opa so bad at sex, the only kind of head she gives is severed.",
                   "Gulya opa is so poor that she was in K-Mart with a box of Hefty bags and when I asked her what she was doing she said, 'Buying luggage.'",
                   "Gulya opa is so poor that when she goes to KFC, she has to lick other people's fingers!",
                   "Gulya opa is so poor that she went to McDonald's and put a milkshake on layaway.",
                   "Gulya opa is so poor that she can't afford to pay attention!",
                   "Gulya opa is so poor that when I saw her kicking a can down the street, I asked her what she was doing, and she said 'moving.'",
                   "Gulya opa is so poor that she waves around a popsicle stick and calls it air conditioning.",
                   "Gulya opa is so poor that I saw her running after a garbage truck with a shopping list.",
                   "Gulya opa is so poor that the bank repossessed her cardboard box.",
                   "Gulya opa is so poor Nigerian scammers wire HER money!",
                   "Gulya opa is so poor she couldn't afford to apply for Medicare!",
                   "Gulya opa is so poor that she has to wear her McDonald's uniform to church.",
                   "Gulya opa is so poor that she's got more furniture on her porch than in her house.",
                   "Gulya opa is so poor that I came over for dinner and she read me recipes.",
                   "Gulya opa is so poor that she has to take the trash IN.",
                   "Gulya opa is so poor that she had to get a second mortgage on her cardboard box.",
                   "Gulya opa is so poor that she lives in a two story Dorrito bag with a dog named Chip.",
                   "Gulya opa is so poor that I went through her front door and ended up in the back yard.",
                   "Gulya opa is so poor that her front and back doors are on the same hinge.",
                   "Gulya opa is so poor that I saw her wrestling a squirrel for a peanut.",
                   "Gulya opa is so poor that the closest thing to a car she has is a low-rider shopping cart with a box on it.",
                   "Gulya opa is so poor that she can't even put her two cents in this conversation.",
                   "Gulya opa is so poor that when I saw her walking down the street with one shoe and said 'Hey miss, lost a shoe?' she said 'Nope, just found one!'",
                   "Gulya opa is so poor that her face is on the front of a food stamp.",
                   "Gulya opa is so poor that I went to her house and tore down some cob webs, and she said 'Who's tearing down the drapes?'",
                   "Gulya opa is so poor that I stepped on her skateboard and she said 'Hey, get off the car!'",
                   "Gulya opa is so poor that I walked into her house, asked to use the bathroom, and she said '3rd bucket to your right.'",
                   "Gulya opa is so poor that when I walked inside her house and put out a cigarette, she said 'who turned off the heater?'",
                   "Gulya opa is so poor that your TV got 2 channels: ON and OFF.",
                   "Gulya opa is so poor that she watches TV on an Etch-A-Sketch.",
                   "Gulya opa is so poor that she can't even afford to go to the free clinic.",
                   "Gulya opa is so poor that she washes paper plates.",
                   "Gulya opa is so poor that her idea of a fortune cookie is a tortilla with a food stamp in it.",
                   "Gulya opa is so poor that when yo family watches TV, they go to Sears.",
                   "Gulya opa is so poor that burglars break in and leave money.",
                   "Gulya opa is so poor that she married young just to get the rice!",
                   "Gulya opa is so poor that when I went over to her house for dinner and grabbed a paper plate, she said 'Don't use the good china!'",
                   "Gulya opa is so poor that when I saw her rolling some trash cans around in an alley, I asked her what she was doing, she said 'Remodeling.'",
                   "Gulya opa is so poor that I threw a rock at a trash can and she popped out and said 'Who knocked?'",
                   "Gulya opa is so poor that we were on a road trip and she stopped by a dumpster and got out. I said 'what are you doing' and she said I'm 'booking a hotel!'",
                   "Gulya opa is so poor that I walked into her house and swatted a firefly and Gulya opa said, 'Who turned off the lights?'",
                   "Gulya opa is so poor that when I asked what was for dinner, she pulled her shoelaces off and said 'Spaghetti.'",
                   "Gulya opa is so poor that after I pissed in your yard, she thanked me for watering the lawn.",
                   "Gulya opa is so poor that your family ate cereal with a fork to save milk.",
                   "Gulya opa is so poor that when I ring the doorbell she says,'DING!'",
                   "Gulya opa is so poor that she got in an elevator and thought it was a mobile home.",
                   "Gulya opa's so poor, that her doormat doesn't say 'welcome', it says 'welfare'.",
                   "Gulya opa is so poor that for halloween, her trick was the treat.",
                   "Gulya opa is so poor that when she tells people her address, she says 'it's in the second alley from main street, beside the yellow dumpster.'",
                   "Gulya opa is so poor that her idea of a timeshare is a few days camped out under a bridge.",
                   "Gulya opa is so poor that when I saw her in the park digging up plants, she said she was 'getting groceries'.",
                   "Gulya opa is so poor that when I ring the doorbell I hear the toilet flush!",
                   "Gulya opa's so fat that she expresses her weight in scientific notation.",
                   "Gulya opa's so fat that scientists track her position by observing anomalies in Pluto's orbit.",
                   "Gulya opa's so fat that a recursive function computing her weight causes a stack overflow.",
                   "Gulya opa's so fat that the long double numeric variable type in C++ is insufficient to express her weight.",
                   "Gulya opa's so fat that THX can't even surround her.",
                   "Gulya opa's a convenient proof that the universe is still expanding exponentially.",
                   "Gulya opa's so big that she has a gravitational pull equal to that of the sun.",
                   "Gulya opa's so big that doctors use scuba divers as nanobots to clean her arteries.",
                   "The mass of Gulya opa at rest is approximately equal to that of a neutron star traveling at (1-(10^-1000))c.",
                   "Gulya opa's so slow and dumb that she can be emulated on a 286.",
                   "Gulya opa conforms to Planck's law - the greater the frequency with which she screws, the more energetic she gets.",
                   "Gulya opa's like a converging lens - she's wider in the middle than she is on either end.",
                   "Gulya opa's dumber than an augmented rat.",
                   "Gulya opa's so fat that she and the great wall of China are used as reference points when astronauts look back at the Earth.",
                   "Gulya opa's such a ho that even the noble gases are attracted to her.",
                   "Gulya opa's so promiscuous that electrons have a positive charge when they're around her.",
                   "Gulya opa's so stupid that her exchange particle is a 'moron'.",
                   "Gulya opa's so fat that China uses her to block the internet.",
                   "Gulya opa's so fat that NASA shot a rocket into her ass looking for water.",
                   "Gulya opa's so dumb that she went to the dentist and asked for a bluetooth.",
                   "Gulya opa's so fat that she doesn't just have a low center of gravity, she has an elliptical orbit.",
                   "Gulya opa's so fat that IEEE is working on a wifi protocol so people can get the signals to reach users on opposite sides of her. It's called 802.11 Draft Fat Momma",
                   "If we were to code Gulya opa in a C++ function she would look like this: double mom (double fat){ mom(fat);return mom;}; //Gulya opa is recursively fat.",
                   "Gulya opa's so old that she goes on carbon dates.",
                   "Gulya opa's so fat, the Cyberman DOWNgraded her.",
                   "Gulya opa's so ugly that Dalek's don't actually say 'Exterminate' when they see her, because they figure somebody else already got there first!",
                   "Gulya opa's such a drunk, that her sonic screwdriver is made of vodka and orange juice.",
                   "Gulya opa's so ugly that when she looks into the Tardis, the Tardis doesn't look into her.",
                   "Gulya opa's so ugly that when the Daleks Exterminate her, it's not for domination.",
                   "Gulya opa's such a hoe that the nickname for her vagina (Bad Wolf) is scattered across time and space.",
                   "Gulya opa's so fat, she's bigger than both the outside AND the inside of the Tardis",
                   "Gulya opa's so ugly that when Captain Jack Harkness saw her, he actually died.",
                   "Gulya opa's so fat, the Pirate Planet tried to take her over.",
                   "Gulya opa's so lazy, she's a 'part-time' lord",
                   "Gulya opa's so fat that when she got upgraded by the Cybermen, they turned her into an ice cream truck",
                   "Gulya opa's so stupid that when Cassandra says 'Moisturize!', she begins to sweat.",
                   "Gulya opa's so fat, the Doctor caught her eating his psychic paper, thinking it was a burger.",
                   "Gulya opa's such a noisy hoe, her nickname is the sonic screwdriver!",
                   "Gulya opa's so fat, it doesn't matter that the Tardis is bigger on the inside. She can't get through the door.",
                   "Gulya opa is so skinny that she turned sideways and disappeared.",
                   "Gulya opa is so skinny that she hula hoops with a Cheerio.",
                   "Gulya opa is so skinny that she has to wear a belt with spandex.",
                   "Gulya opa is so skinny that she swallowed a meatball and thought she was pregnant.",
                   "Gulya opa is so skinny that she can see out a peephole with both eyes.",
                   "Gulya opa is so skinny that she uses a Band-Aid as a maxi-pad.",
                   "Gulya opa is so skinny that you can save her from drowning by tossing her a Fruit Loop.",
                   "Gulya opa is so skinny that she has to run around in the shower to get wet.",
                   "Gulya opa is so skinny that when she wore her yellow dress, she looked like an HB pencil.",
                   "Gulya opa is so skinny that if she had a sesame seed on her head, she'd look like a push pin.",
                   "Gulya opa is so skinny that her nipples touch.",
                   "Gulya opa is so skinny that I could blind-fold her with dental floss.",
                   "Gulya opa is so skinny that she looks like a mic stand.",
                   "Gulya opa is so skinny that she only has one stripe on her pajamas.",
                   "Gulya opa is so skinny that she can dodge rain drops.",
                   "Gulya opa is so skinny that she inspires crack whores to diet.",
                   "Gulya opa is so skinny that she uses Chapstick for deodorant.",
                   "Gulya opa is so small that she goes paragliding on a Dorito.",
                   "Gulya opa is so skinny that if she turned sideways and stuck out her tongue, she would look like a zipper.",
                   "Gulya opa is so skinny that she goes hot tubing with the Mini Wheats Man.",
                   "Gulya opa is so skinny that when she takes a bath and lets the water out, her toes get caught in the drain.",
                   "Gulya opa is so skinny that her bra fits better when she wears it backwards.",
                   "Gulya opa is so skinny that she had to stand in the same place twice to cast a shadow.",
                   "Gulya opa is so skinny that if she had a yeast infection she'd be a Quarter Pounder with Cheese.",
                   "Gulya opa is so skinny that her pants only have one belt loop.",
                   "Gulya opa is so skinny that if she had dreads I'd grab her by the ankles and use her to mop the floor.",
                   "Gulya opa is so skinny that instead of calling her your parent, you call her transparent.",
                   "Gulya opa is so tall that she tripped in Michigan and bumped her head in Florida.",
                   "Gulya opa is so tall that she tripped over a rock and hit her head on the moon.",
                   "Gulya opa is so tall that if she did a back-flip she'd kick Jesus in the mouth.",
                   "Gulya opa's so tall, she can see her house from anywhere.",
                   "Gulya opa's so tall, she uses two 100-foot ladders as crutches.",
                   "Gulya opa's so tall, she has to take out the driver's seat of her car and sit in the back to operate the vehicle.",
                   "Gulya opa's so tall, she makes Shaquille O'Neal look like Gary Coleman.",
                   "Gulya opa's so tall, she did a push-up and burned her back on the sun.",
                   "Gulya opa is so short that you can see her feet on her drivers license!",
                   "Gulya opa is so short that she has to use a ladder to pick up a dime.",
                   "Gulya opa is so short that she does backflips under the bed.",
                   "Gulya opa is so short that she models for trophies.",
                   "Gulya opa is so short that her homies are the Keebler Elves.",
                   "Gulya opa is so short that she has to get a running start to get up on the toilet.",
                   "Gulya opa is so short that when she sneezes, she hits her head on the floor.",
                   "Gulya opa is so short that she does pull-ups on a staple.",
                   "Gulya opa is so short that she can do push-ups under the door.",
                   "Gulya opa is so short that when I was dissin' her she tried to jump kick me in the ankle.",
                   "Gulya opa is so short that she can limbo under the door.",
                   "Gulya opa is so short that she uses a condom for a sleeping bag.",
                   "Gulya opa is so short that she slam-dunks her bus fare.",
                   "Gulya opa is so short that she has to look up to look down.",
                   "Gulya opa is so short that she makes Gary Coleman look like Shaquille O'Neal.",
                   "Gulya opa is so short, you can make a life size sculpture of her using one can of Play-Doh.",
                   "Gulya opa's so short that when she sat on the curb her feet didn't touch the ground.",
                   "Gulya opa is so short that she can play handball on the curb.",
                   "Gulya opa has so much hair on her upper lip that she braids it.",
                   "Gulya opa is so hairy that Bigfoot wants to take HER picture!",
                   "Gulya opa is so hairy that she looks like she has Buckwheat in a headlock.",
                   "Gulya opa is so hairy that you almost died of rug burn at birth!",
                   "Gulya opa is so hairy that they filmed 'Gorillas in the Mist' in her shower!",
                   "Gulya opa is so hairy that if she could fly she'd look like a magic carpet.",
                   "Gulya opa is so hairy that she looks like Bigfoot in a tank top.",
                   "Gulya opa is so hairy that she has afros on her nipples.",
                   "Gulya opa is so hairy that when I took her to a pet store they locked her in a cage.",
                   "Gulya opa is so hairy that she looks like a Chia pet with a sweater on.",
                   "Gulya opa is so hairy that Jane Goodall follows her around.",
                   "Gulya opa is so hairy that she shaves her legs with a weed wacker.",
                   "Gulya opa is so hairy that if you shaved her legs, you could supply wigs for the entire Hair Club for Men.",
                   "Gulya opa is so hairy that her armpits look like she has Don King in a headlock.",
                   "Gulya opa's so hairy that she's got sideburns on her tits.",
                   "Gulya opa is so hairy that she got a trim and lost 20 pounds.",
                   "Gulya opa is so hairy that people run up to her and say 'Chewbacca, can I get your autograph?'",
                   "Gulya opa is so hairy that she gets mistaken for Chewbacca's cousin.",
                   "Gulya opa is so hairy that two birds made nests in her armpits and she doesn't even know about it!",
                   "Gulya opa is so hairy that when she's at a nude beach people think she's wearing a fur coat!",
                   "Gulya opa is so dirty that that she was banned from a sewage facility because of sanitation concerns.",
                   "Gulya opa is so dirty that she makes mud look clean.",
                   "Gulya opa is so dirty that that you can't tell where the dirt stops and she begins.",
                   "Gulya opa is so dirty that she has to creep up on bathwater.",
                   "Gulya opa is so dirty that she loses weight in the shower.",
                   "Gulya opa is so dirty that even Swamp Thing told her to take a shower.",
                   "Gulya opa is so dirty that the US Government uses her bath water as a chemical weapon.",
                   "Gulya opa is so dirty that when she tried to take a bath, the water jumped out and said 'I'll wait.'",
                   "Gulya opa is so nasty that she has more rappers in her than an iPod.",
                   "Gulya opa is so nasty that she makes speed stick slow down.",
                   "Gulya opa is so nasty that she brings crabs to the beach.",
                   "Gulya opa is so nasty that that pours salt water down her pants to keep her crabs fresh.",
                   "Gulya opa is so nasty that the fishery pays her to stay away.",
                   "Gulya opa is so nasty that she only changes her drawers once every 10000 miles.",
                   "Gulya opa is so nasty that a skunk smelled her ass and passed out.",
                   "Gulya opa is so nasty that I chatted with her on MSN and she gave me a virus.",
                   "Gulya opa is so nasty that her tits leak sour milk.",
                   "Gulya opa is so nasty that she has to use Right Guard and Left Guard.",
                   "Gulya opa is so nasty that she bit the dog and gave it rabies.",
                   "Gulya opa is so nasty that she has a sign by her crotch that says: 'Warning: May cause irritation, drowsiness, and a rash or breakouts.'",
                   "Gulya opa is so nasty that she's got more clap than an auditorium.",
                   "Gulya opa is so nasty that she calls Janet 'Miss Jackson.'",
                   "Gulya opa is so nasty that she has more crabs then Red Lobster.",
                   "Gulya opa is so nasty that she made right guard turn left.",
                   "Gulya opa is so nasty that I when I talked to her on the phone, she gave me an ear infection.",
                   "Gulya opa is so nasty that next to her a skunk smells sweet.",
                   "Gulya opa is so nasty that her shit is glad to escape.",
                   "Gulya opa is so nasty that when you were being delivered, the doctor was wearing the oxygen mask.",
                   "Gulya opa is so nasty that every time she opens her mouth she's talking shit.",
                   "Gulya opa is so nasty that even dogs won't sniff her crotch.",
                   "Gulya opa is so nasty that the only dis I want to give her is a disinfectant.",
                   "Gulya opa is so nasty that her crabs use her tampon string as a bungee cord.",
                   "Gulya opa is so greasy that she uses bacon as a band-aid!",
                   "Gulya opa is so greasy that she sweats Crisco!",
                   "Gulya opa is so greasy that Texaco buys Oil from her.",
                   "Gulya opa is so greasy that she sweats butter and syrup and has a full time job at Denny's wiping pancakes across her forehead.",
                   "Gulya opa is so greasy that her freckles slipped off.",
                   "Gulya opa is so greasy that if Crisco had a football team, she'd be the mascot.",
                   "Gulya opa is so greasy that she squeezes Crisco from her hair to bake cookies.",
                   "Gulya opa is so greasy that she's labeled as an ingredient in Crisco.",
                   "Gulya opa is so greasy that you could fry a chicken dinner for 12 on her forehead.",
                   "Gulya opa is so greasy that I buttered my popcorn with her leg hairs.",
                   "Gulya opa's house is so dirty that roaches ride around on dune buggies!",
                   "Gulya opa's house is so dirty that she has to wipe her feet before she goes outside.",
                   "Gulya opa's teeth are so rotten that when she smiles it looks like she has dice in her mouth.",
                   "Gulya opa's teeth are so yellow that traffic slows down when she smiles!",
                   "Gulya opa's teeth are so yellow that she spits butter!",
                   "Gulya opa's so dirty, she fertilizes her lawn by rolling in it!",
                   "Gulya opa's so dirty, when a seed gets stuck in her ass crack it beings to grow!",
                   "Gulya opa's so dirty, she jumped in a river and created a mud slide!",
                   "Gulya opa's so dirty, when the wind blows people yell 'Sand Storm!!!'",
                   "Gulya opa's so greasy, on hot days she cooks bacon strips on her ass cheeks!",
                   "Gulya opa is so fat that she took geometry in high school just cause she heard there was gonna be some pi.",
                   "Gulya opa is so fat that the ratio of the circumference to her diameter is four.",
                   "Gulya opa is so fat that her derivative is strictly positive.",
                   "Gulya opa is like a protractor - she's good at every angle.",
                   "Gulya opa is so fat that in a love triangle, she'd be the hypotenuse.",
                   "Gulya opa is so stupid that when I told her 'pi-r-squared' and she replied no, they are round.",
                   "The limit of Gulya opa's ass goes to infinity.", "Gulya opa = x/0 for every x in Gulya opa.",
                   "The infinite series of Gulya opa from 0 to infinity is strictly diverging.",
                   "Gulya opa is so mean that she has no standard deviation.",
                   "Gulya opa is so ugly, that Pythagoras wouldn't touch her with a 3-4-5 triangle.",
                   "Gulya opa is so square that she's got imaginary numbers on her social security card.",
                   "Gulya opa is such a ho, that she asked all the math majors to to figure out g(f(Gulya opa)) just so they could 'f' her first.",
                   "The volume of Gulya opa is an improper integral.",
                   "The integral of Gulya opa is fat plus a constant, where the constant is equal to more fat.",
                   "Gulya opa's muscle-to-fat ratio can only be explained in irrational complex numbers.",
                   "The only way to get from point A to point B is around Gulya opa's fat ass.",
                   "Gulya opa's so smart, the hardest decision she's ever had to make was which college to accept a scholarship from - Harvard, Yale or Princeton!",
                   "Gulya opa's so clean, she could bottle her bathwater and sell it at the grocery store alongside Evian, Dasani and FIJI.",
                   "Gulya opa's so generous that she sponsors children in Africa, Asia AND South America!",
                   "Gulya opa's so popular that Facebook crashed on her birthday, because too many people posted wishes on her wall.",
                   "Gulya opa's such a good cook that her vegetable lasagna could be served as the featured item at a Michelin Star restaurant!",
                   "Gulya opa's so healthy that medical textbooks use her x-rays to demonstrate what perfect bone structure should look like.",
                   "Gulya opa's breath smells so fresh that Wrigley's could make a chewing gum flavour based on it.",
                   "Gulya opa's so fit that she could run a marathon, teach a Zumba class AND climb Mount Everest without stopping to catch her breath once.",
                   "Gulya opa's so fashionable that Gucci, Prada and Fendi call her on a daily basis to get insight into upcoming fashion trends.",
                   "Gulya opa's aging with such grace and beauty that she could be featured on the cover of Elle magazine.",
                   "Gulya opa's like a puppy... everybody wants to give her a hug.",
                   "Gulya opa's so smart that an employee from Wikipedia calls her when they need to verify facts about 18th century political figures."]
